### ISSUE TITLE
Can't add schema retrospectivly

### ISSUE THREAD

**Issue by richardjpope** [theodi/octopub#885] opened 2018-11-19 21:06 UTC
### Expected Behaviour
I should be able to create a schema and apply it to a colleciton.

### Current Behaviour (for problems)
Schema are only avaliable to apply to a dataset (via the edit or create form) if they already existed at the time the collection was created.

### Steps to Reproduce (for problems)
> Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant
1. Create a colletion
2. Create a schema
3. Try and apply the schema to the collection
4.

### Your Environment
Ipad Safari

**Comment by rachelwilson** [comment] 2020-05-12 11:47
Is this a duplicate of https://github.com/theodi/octopub/issues/953?

**Comment by caiwilliamson** [comment] 2020-06-08 21:03
Closing this since it's a duplicate of #953

**Closed by caiwilliamson** 2020-06-08 21:03 UTC
Labels: p:high, problem:bug
