### ISSUE TITLE
If a CSV has any blank fields the infer dataset file schema does not work

### ISSUE THREAD

**Issue by peterkwells** [theodi/octopub#410] opened 2017-04-20 15:53 UTC
(Feedback from FSA phase 3)

![Uploading Screen Shot 2017-04-20 at 16.52.27.png…]()

**Comment by Floppy** [comment] 2017-04-21 11:53
This should be handled, I'll look into it.

**Comment by Floppy** [comment] 2017-05-04 14:11
Confirmed: 

<img width="968" alt="screen shot 2017-05-04 at 15 10 58" src="https://cloud.githubusercontent.com/assets/3565/25707592/f338a052-30db-11e7-8831-b4c46a94bd04.png">

**Comment by Floppy** [comment] 2017-05-04 14:11
thanks, tooltips. Thooltips.

**Comment by Floppy** [comment] 2017-05-04 15:36
I'm chasing this down, but I can't get it to replicate in tests yet, which also makes me worry about at least one other test.

**Comment by Floppy** [comment] 2017-05-09 17:07
OK, worked out why the mocking isn't working. At least one other test isn't testing correctly because of this.

**Comment by Floppy** [comment] 2017-05-09 17:07
Cryptic.

**Comment by Floppy** [comment] 2017-05-09 17:26
OK replicated a failing test for this in #425. The actual error it seems is inside the `jsontableschema` gem, so now I have this isolated, I'll dig down into there and fix it. Baby steps.

**Comment by Floppy** [comment] 2017-05-17 13:12
Fix is in #425, just waiting for review and then I'll merge it in and deploy.

**Closed** 2017-05-17 14:17 UTC
Labels: bug, FSA team raised issue

**Comment by peterkwells** [comment] 2017-05-22 09:29
Reported to FSA and asked them to retest
